# Generated by Django 3.0.3 on 2020-09-09 16:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AI_table',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('AI_Name', models.CharField(max_length=10)),
                ('AI_Filename', models.CharField(max_length=25)),
                ('ACC', models.FloatField(blank=True, null=True)),
                ('Description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Stock_table',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Stock_id', models.IntegerField()),
                ('Stock_Date', models.DateTimeField()),
                ('Stock_Sym', models.CharField(max_length=5)),
                ('Stock_open', models.FloatField()),
                ('Stock_close', models.FloatField()),
                ('Stock_high', models.FloatField()),
                ('Stock_low', models.FloatField()),
                ('Stock_vol', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Indicator_table',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('indicator_id', models.IntegerField()),
                ('indicator_type', models.CharField(max_length=15)),
                ('value', models.FloatField()),
                ('stock_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='research.Stock_table')),
            ],
        ),
    ]
